# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python-textbundle',
                'doc_host': 'https://kcaylor.github.io',
                'git_url': 'https://github.com/kcaylor/python-textbundle',
                'lib_path': 'python_textbundle'},
  'syms': {'python_textbundle.core': {'python_textbundle.core.foo': ('core.html#foo', 'python_textbundle/core.py')}}}